on:
    push
jobs:
    idle:
        runs-on: ubuntu-latest
        steps:
            -
                run: |
                    echo Idle Sleep
                    sleep 10
                    echo Waking up
